[workspace]
channels = ["conda-forge"]
name = "simra"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"
pip = ">=25.1.1,<26"
numpy = ">=2.2.6,<3"
matplotlib = ">=3.10.3,<4"
scikit-learn = ">=1.6.1,<2"
ipykernel = ">=6.29.5,<7"
seaborn = ">=0.13.2,<0.14"
ipywidgets = ">=8.1.7,<9"
lifelines = ">=0.30.0,<0.31"
statsmodels = ">=0.14.4,<0.15"
jinja2 = ">=3.1.6,<4"
ucimlrepo = ">=0.0.7,<0.0.8"
pydicom = ">=3.0.1,<4"
nibabel = ">=5.3.2,<6"
umap-learn = ">=0.5.7,<0.6"
scikit-survival = ">=0.24.1,<0.25"
